# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Daniel Shao
tagline:          'HST and Chess'
description:      'A blog of Daniel Shao's PhD journey at Harvard-MIT's MEMP program.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Daniel Shao'
  url:            github.com/danielshaowers

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
