# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Daniel Shao
tagline:          'HST and Chess'
description:      "I just want to cure cancer, play chess, and spend time with my wonderful partner"
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Daniel Shao'
  url:            github.com/danielshaowers

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
